all:
	cd .. && make

clean:
	cd .. && make clean

cli:
	cd .. && make cli && make install

plugin:
	cd .. && make plugin && make install

format:
	cd .. && make format

test:
	cd .. && make test && make install

gbench:
	cd .. && make gbench && make install

install:
	cd .. && make install
