name: Build GPU-powered package

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build-gpu-linux:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        path: gpu
    - uses: Jimver/cuda-toolkit@v0.2.11
      id: cuda-toolkit
      with:
        cuda: '11.5.1'
        sub-packages: '["nvcc"]'
        method: 'network'
    - name: Install ArrayFire
      working-directory: ${{github.workspace}}/gpu
      run: |
        wget --quiet https://arrayfire.s3.amazonaws.com/3.8.0/ArrayFire-v3.8.0_Linux_x86_64.sh
        chmod +x ./ArrayFire-v3.8.0_Linux_x86_64.sh
        ./ArrayFire-v3.8.0_Linux_x86_64.sh --skip-license --include-subdir --prefix=/opt
        ls /opt
    - name: Configure CMake
      working-directory: ${{github.workspace}}/gpu
      run: |
        export AF_PATH=/opt/arrayfire
        export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${AF_PATH}/lib64
        cmake -B build -DCMAKE_BUILD_TYPE=Release -DEDM_WITH_ARRAYFIRE=ON -DArrayFire_DIR=/opt/arrayfire/cmake
    - name: Build plugin
      working-directory: ${{github.workspace}}/gpu
      run: cmake --build build --target edm_plugin
    - name: Install plugin
      working-directory: ${{github.workspace}}/gpu
      run: cmake --build build --target install
    - name: Archive plugin
      uses: actions/upload-artifact@v4
      with:
        name: edm_Unix_x64_gpu.plugin
        path: ${{github.workspace}}/gpu/bin/edm_Unix_x64_gpu.plugin
