name: Run unit tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  unit-test-asan-linux:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        path: x64
    - name: Install Catch2
      run: |
        sudo apt-get update
        sudo apt-get install -y libcatch2-dev
    - name: Configure CMake
      working-directory: ${{github.workspace}}/x64
      env:
        CC: clang-17
        CXX: clang++-17
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug
    - name: Build unit tests with address sanitizer
      working-directory: ${{github.workspace}}/x64
      run: cmake --build build --target edm_test
    # - name: Build CLI with address sanitizer
    #   working-directory: ${{github.workspace}}/x64
    #   run: cmake --build build --target edm_cli --parallel 8
    - name: Install unit tests
      working-directory: ${{github.workspace}}/x64
      run: cp build/edm_test test
    # - name: Install CLI
    #   working-directory: ${{github.workspace}}/x64
    #   run: cp build/edm_cli test
    - name: Run unit tests with address sanitizer
      working-directory: ${{github.workspace}}/x64/test
      run: ./edm_test
    # - name: Run CLI test with address sanitizer
    #   working-directory: ${{github.workspace}}/x64/test
    #   run: ./edm_cli ci-test.json

  unit-test-asan-mac-arm:
    runs-on: macos-14
    steps:
    - name: Checkout a copy to compile for ARM
      uses: actions/checkout@v4
      with:
        path: arm
    - name: Install Catch2
      run: brew install catch2
    - name: Configure CMake
      working-directory: ${{github.workspace}}/arm
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH="$(brew --prefix)"
    - name: Build unit tests with address sanitizer
      working-directory: ${{github.workspace}}/arm
      run: cmake --build build --target edm_test --parallel 8
    - name: Build CLI with address sanitizer
      working-directory: ${{github.workspace}}/arm
      run: cmake --build build --target edm_cli --parallel 8
    - name: Install unit tests
      working-directory: ${{github.workspace}}/arm
      run: cp build/edm_test test
    - name: Install CLI
      working-directory: ${{github.workspace}}/arm
      run: cp build/edm_cli test
    - name: Run unit tests with address sanitizer
      working-directory: ${{github.workspace}}/arm/test
      run: ./edm_test
    # - name: Run CLI test with address sanitizer
    #   working-directory: ${{github.workspace}}/arm/test
    #   run: ./edm_cli ci-test.json

  unit-test-asan-mac-x64:
    runs-on: macos-14
    steps:
    - name: Checkout a copy to compile for x86
      uses: actions/checkout@v4
      with:
        path: x64
    - name: Install Catch2
      run: brew install catch2
    - name: Configure CMake
      working-directory: ${{github.workspace}}/x64
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH="$(brew --prefix)"
    - name: Build unit tests with address sanitizer
      working-directory: ${{github.workspace}}/x64
      run: cmake --build build --target edm_test
    # - name: Build CLI with address sanitizer
    #   working-directory: ${{github.workspace}}/x64
    #   run: cmake --build build --target edm_cli --parallel 8
    - name: Install unit tests
      working-directory: ${{github.workspace}}/x64
      run: cp build/edm_test test
    # - name: Install CLI
    #   working-directory: ${{github.workspace}}/x64
    #   run: cp build/edm_cli test
    - name: Run unit tests with address sanitizer
      working-directory: ${{github.workspace}}/x64/test
      run: ./edm_test
    # - name: Run CLI test with address sanitizer
    #   working-directory: ${{github.workspace}}/x64/test
    #   run: ./edm_cli ci-test.json

  unit-test-asan-windows:
    runs-on: windows-2019
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        path: x64
    - name: Install Catch2
      run: vcpkg install catch2:x64-windows
    - name: Configure CMake
      working-directory: ${{github.workspace}}/x64
      run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug
    - name: Build unit tests (todo -- need to get Debug version working here)
      working-directory: ${{github.workspace}}/x64
      run: cmake --build build --config Release --target edm_test
    # - name: Build CLI with address sanitizer
      # working-directory: ${{github.workspace}}/x64
      # run: cmake --build build --config Debug --target edm_cli
    # - name: Install unit tests
    #   working-directory: ${{github.workspace}}/x64
    #   run: cp build/Release/edm_test.exe test
    # - name: Install CLI
    #   working-directory: ${{github.workspace}}/x64
    #   run: cp build/Debug/edm_cli.exe test
    - name: Run unit tests (from Release dir, as Catch2 now has .dlls)
      working-directory: ${{github.workspace}}/x64/build/Release
      run: .\edm_test.exe
    # - name: Run CLI test with address sanitizer
    #   working-directory: ${{github.workspace}}/x64/test
    #   run: .\edm_cli.exe ci-test.json
